// Auto-generated by scripts/build-image-manifest.ts. Do not edit directly.

export const images = {
  "/images/hackathons/red-white-build/certificate.webp": {
    "path": "/images/hackathons/red-white-build/certificate.webp",
    "width": 2400,
    "height": 1828,
    "aspectRatio": 1.3129
  },
  "/images/hackathons/red-white-build/photo-01.webp": {
    "path": "/images/hackathons/red-white-build/photo-01.webp",
    "width": 2400,
    "height": 1347,
    "aspectRatio": 1.7817
  },
  "/images/hackathons/red-white-build/photo-02.webp": {
    "path": "/images/hackathons/red-white-build/photo-02.webp",
    "width": 2400,
    "height": 1347,
    "aspectRatio": 1.7817
  },
  "/images/hackathons/red-white-build/photo-03.webp": {
    "path": "/images/hackathons/red-white-build/photo-03.webp",
    "width": 2400,
    "height": 1802,
    "aspectRatio": 1.3319
  },
  "/images/hackathons/red-white-build/photo-04.webp": {
    "path": "/images/hackathons/red-white-build/photo-04.webp",
    "width": 2400,
    "height": 1802,
    "aspectRatio": 1.3319
  },
  "/images/hackathons/red-white-build/photo-05.webp": {
    "path": "/images/hackathons/red-white-build/photo-05.webp",
    "width": 2400,
    "height": 1802,
    "aspectRatio": 1.3319
  },
  "/images/hackathons/red-white-build/photo-06.webp": {
    "path": "/images/hackathons/red-white-build/photo-06.webp",
    "width": 2400,
    "height": 1802,
    "aspectRatio": 1.3319
  },
  "/images/portrait/portrait-about.webp": {
    "path": "/images/portrait/portrait-about.webp",
    "width": 2400,
    "height": 2400,
    "aspectRatio": 1
  },
  "/images/portrait/portrait-cutout.webp": {
    "path": "/images/portrait/portrait-cutout.webp",
    "width": 843,
    "height": 1370,
    "aspectRatio": 0.6153
  },
  "/images/portrait/portrait.webp": {
    "path": "/images/portrait/portrait.webp",
    "width": 1122,
    "height": 1402,
    "aspectRatio": 0.8003
  },
  "/images/projects/gikuyu-translator/capture-desktop-full.webp": {
    "path": "/images/projects/gikuyu-translator/capture-desktop-full.webp",
    "width": 1440,
    "height": 2030,
    "aspectRatio": 0.7094
  },
  "/images/projects/gikuyu-translator/capture-desktop.webp": {
    "path": "/images/projects/gikuyu-translator/capture-desktop.webp",
    "width": 2400,
    "height": 1500,
    "aspectRatio": 1.6
  },
  "/images/projects/gikuyu-translator/capture-mobile.webp": {
    "path": "/images/projects/gikuyu-translator/capture-mobile.webp",
    "width": 1109,
    "height": 2400,
    "aspectRatio": 0.4621
  },
  "/images/projects/gikuyu-translator/cover.webp": {
    "path": "/images/projects/gikuyu-translator/cover.webp",
    "width": 2400,
    "height": 1500,
    "aspectRatio": 1.6
  },
  "/images/projects/oppolia/capture-desktop-full.webp": {
    "path": "/images/projects/oppolia/capture-desktop-full.webp",
    "width": 1440,
    "height": 9113,
    "aspectRatio": 0.158
  },
  "/images/projects/oppolia/capture-desktop.webp": {
    "path": "/images/projects/oppolia/capture-desktop.webp",
    "width": 2400,
    "height": 1500,
    "aspectRatio": 1.6
  },
  "/images/projects/oppolia/capture-mobile.webp": {
    "path": "/images/projects/oppolia/capture-mobile.webp",
    "width": 1109,
    "height": 2400,
    "aspectRatio": 0.4621
  },
  "/images/projects/oppolia/cover.webp": {
    "path": "/images/projects/oppolia/cover.webp",
    "width": 2400,
    "height": 1500,
    "aspectRatio": 1.6
  },
  "/images/projects/saka/capture-desktop-full.webp": {
    "path": "/images/projects/saka/capture-desktop-full.webp",
    "width": 1440,
    "height": 4044,
    "aspectRatio": 0.3561
  },
  "/images/projects/saka/capture-desktop.webp": {
    "path": "/images/projects/saka/capture-desktop.webp",
    "width": 2400,
    "height": 1500,
    "aspectRatio": 1.6
  },
  "/images/projects/saka/capture-mobile.webp": {
    "path": "/images/projects/saka/capture-mobile.webp",
    "width": 1109,
    "height": 2400,
    "aspectRatio": 0.4621
  },
  "/images/projects/saka/cover.webp": {
    "path": "/images/projects/saka/cover.webp",
    "width": 2400,
    "height": 1500,
    "aspectRatio": 1.6
  },
  "/images/projects/smart-chama/capture-desktop-full.webp": {
    "path": "/images/projects/smart-chama/capture-desktop-full.webp",
    "width": 1440,
    "height": 5372,
    "aspectRatio": 0.2681
  },
  "/images/projects/smart-chama/capture-desktop.webp": {
    "path": "/images/projects/smart-chama/capture-desktop.webp",
    "width": 2400,
    "height": 1500,
    "aspectRatio": 1.6
  },
  "/images/projects/smart-chama/capture-mobile.webp": {
    "path": "/images/projects/smart-chama/capture-mobile.webp",
    "width": 1109,
    "height": 2400,
    "aspectRatio": 0.4621
  },
  "/images/projects/smart-chama/cover.webp": {
    "path": "/images/projects/smart-chama/cover.webp",
    "width": 2400,
    "height": 1500,
    "aspectRatio": 1.6
  },
  "/images/projects/sucre-bushworks/capture-desktop-full.webp": {
    "path": "/images/projects/sucre-bushworks/capture-desktop-full.webp",
    "width": 1440,
    "height": 6786,
    "aspectRatio": 0.2122
  },
  "/images/projects/sucre-bushworks/capture-desktop.webp": {
    "path": "/images/projects/sucre-bushworks/capture-desktop.webp",
    "width": 2400,
    "height": 1500,
    "aspectRatio": 1.6
  },
  "/images/projects/sucre-bushworks/capture-mobile.webp": {
    "path": "/images/projects/sucre-bushworks/capture-mobile.webp",
    "width": 1109,
    "height": 2400,
    "aspectRatio": 0.4621
  },
  "/images/projects/sucre-bushworks/cover.webp": {
    "path": "/images/projects/sucre-bushworks/cover.webp",
    "width": 2400,
    "height": 1500,
    "aspectRatio": 1.6
  }
} as const;

export type ImagePath = keyof typeof images;
