import fs from 'node:fs';
import path from 'node:path';
import { baseModes, realmTokens, giediRealmTokens } from '../src/design/tokens';

function formatBlock(selector: string, values: Record<string, string> | object): string {
  const lines = Object.entries(values).map(([key, val]) => {
    const cssVar =
      key === 'ink2'
        ? '--ink-2'
        : key === 'accentInk'
        ? '--accent-ink'
        : key === 'lineAlpha'
        ? '--line-alpha'
        : key === 'colorScheme'
        ? 'color-scheme'
        : `--${key}`;
    return `  ${cssVar}: ${val};`;
  });
  return `${selector} {\n${lines.join('\n')}\n}`;
}

function main() {
  const css = `/* Auto-generated by scripts/build-tokens.ts. Do not edit directly. */

${formatBlock(':root,\n[data-theme="arrakis"]', baseModes.arrakis)}

${formatBlock('[data-theme="giedi"]', baseModes.giedi)}

@media (prefers-color-scheme: dark) {
${formatBlock('  :root:not([data-theme])', baseModes.giedi).replace(/^/gm, '  ').trimEnd()}
}

/* Realms in Arrakis (light mode) */
${formatBlock('[data-realm="fremen"]', realmTokens.fremen)}

${formatBlock('[data-realm="atreides"]', realmTokens.atreides)}

${formatBlock('[data-realm="corrino"]', realmTokens.corrino)}

/* Realms in Giedi (dark mode / black sun) */
${formatBlock('[data-theme="giedi"] [data-realm="fremen"]', giediRealmTokens.fremen)}

${formatBlock('[data-theme="giedi"] [data-realm="atreides"]', giediRealmTokens.atreides)}

${formatBlock('[data-theme="giedi"] [data-realm="corrino"]', giediRealmTokens.corrino)}

/* Print (CV PDF): always the light palette, whatever mode the reader is in */
@media print {
${[
  formatBlock(':root,\n[data-theme]', baseModes.arrakis),
  formatBlock('[data-realm="fremen"],\n[data-theme] [data-realm="fremen"]', realmTokens.fremen),
  formatBlock('[data-realm="atreides"],\n[data-theme] [data-realm="atreides"]', realmTokens.atreides),
  formatBlock('[data-realm="corrino"],\n[data-theme] [data-realm="corrino"]', realmTokens.corrino),
]
  .map((b) => b.replace(/^/gm, '  '))
  .join('\n\n')}
}
`;

  const outputPath = path.resolve('src/app/tokens.generated.css');
  fs.writeFileSync(outputPath, css, 'utf-8');
  console.log(`Generated ${outputPath}`);
}

main();
