import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';

interface ImageMeta {
  path: string;
  width: number;
  height: number;
  aspectRatio: number;
}

function findWebpFiles(dir: string): string[] {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === '_inbox') continue;
      files.push(...findWebpFiles(fullPath));
    } else if (entry.isFile() && entry.name.endsWith('.webp')) {
      files.push(fullPath);
    }
  }

  return files;
}

async function main() {
  const publicDir = path.resolve('public');
  const imagesDir = path.join(publicDir, 'images');

  if (!fs.existsSync(imagesDir)) {
    console.error(`Images directory not found: ${imagesDir}`);
    process.exit(1);
  }

  const files = findWebpFiles(imagesDir);
  const manifest: Record<string, ImageMeta> = {};

  for (const file of files) {
    const relToPublic = path.relative(publicDir, file).split(path.sep).join('/');
    const key = `/${relToPublic}`;
    const meta = await sharp(file).metadata();
    const width = meta.width ?? 0;
    const height = meta.height ?? 0;
    const aspectRatio = height > 0 ? Number((width / height).toFixed(4)) : 1;

    manifest[key] = {
      path: key,
      width,
      height,
      aspectRatio,
    };
  }

  const sortedKeys = Object.keys(manifest).sort();
  const sortedManifest: Record<string, ImageMeta> = {};
  for (const k of sortedKeys) {
    sortedManifest[k] = manifest[k];
  }

  const contentDir = path.resolve('src/content');
  if (!fs.existsSync(contentDir)) {
    fs.mkdirSync(contentDir, { recursive: true });
  }

  const outputPath = path.join(contentDir, 'images.generated.ts');
  const fileContent = `// Auto-generated by scripts/build-image-manifest.ts. Do not edit directly.

export const images = ${JSON.stringify(sortedManifest, null, 2)} as const;

export type ImagePath = keyof typeof images;
`;

  fs.writeFileSync(outputPath, fileContent, 'utf-8');
  console.log(`Generated ${outputPath} with ${sortedKeys.length} images.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
